---

- name: List hosts in ESXi
  ansible.builtin.debug:
    msg: "Host: {{ item }}"
  loop: "{{ groups['esxi'] }}"

- name: List hosts in VC
  ansible.builtin.debug:
    msg: "Host: {{ item }}"
  loop: "{{ groups['vc'] }}"

- name: "DELETE virtual machine {{ host_fact_name }}"
  community.vmware.vmware_guest:
    datacenter: "{{ vc_datacenter }}"
    folder: "{{ vc_datacenter }}/vm/{{ vc_folder }}"
    name: "{{ host_fact_name }}"
    state: absent
    force: true
  when: removevsphere | bool
